services:
  # Production application server
  app:
    image: collider-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collider_app_prod
    environment:
      ENVIRONMENT: production
      PORT: 8880
      RUST_LOG: info
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "8880:8880"
    networks:
      - collider
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8880/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  collider:
    driver: bridge