services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: collider_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - collider
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Dragonfly Cache (Redis-compatible) - Local instance for development
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.25.1
    container_name: collider_dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data
    command: dragonfly --logtostderr --maxmemory=1gb --cache_mode=true --proactor_threads=2
    networks:
      - collider
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
    driver: local
  dragonfly_data:
    driver: local

networks:
  collider:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16