[package]
name = "user-dao"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-postgres.workspace = true
tracing.workspace = true
async-trait.workspace = true
chrono.workspace = true
sql-connection.workspace = true
user-models.workspace = true
user-commands.workspace = true
user-errors.workspace = true
database-traits.workspace = true
dao-utils.workspace = true

[dev-dependencies]
test-utils.workspace = true
tokio.workspace = true
serde.workspace = true