{{- if .Values.dragonfly.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collider.fullname" . }}-dragonfly
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collider.dragonfly.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "collider.dragonfly.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "collider.dragonfly.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: dragonfly
        image: "{{ .Values.dragonfly.image.repository }}:{{ .Values.dragonfly.image.tag }}"
        imagePullPolicy: {{ .Values.dragonfly.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.dragonfly.config.port }}
          name: dragonfly
        envFrom:
        - secretRef:
            name: {{ include "collider.fullname" . }}-dragonfly-secret
        command:
        - dragonfly
        args:
        - --logtostderr
        {{- if .Values.dragonfly.config.cacheMode }}
        - --cache_mode=true
        {{- end }}
        - --port={{ .Values.dragonfly.config.port }}
        - --maxmemory={{ .Values.dragonfly.config.maxMemory }}
        - --requirepass=$(DFLY_requirepass)
        volumeMounts:
        {{- if .Values.dragonfly.persistence.enabled }}
        - name: dragonfly-storage
          mountPath: /data
        {{- end }}
        {{- if .Values.dragonfly.healthcheck.enabled }}
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(DFLY_requirepass)
            - ping
          initialDelaySeconds: {{ .Values.dragonfly.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.dragonfly.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.dragonfly.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.dragonfly.healthcheck.failureThreshold }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - $(DFLY_requirepass)
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        {{- end }}
        {{- include "collider.resources" .Values.dragonfly | nindent 8 }}
      volumes:
      {{- if .Values.dragonfly.persistence.enabled }}
      - name: dragonfly-storage
        persistentVolumeClaim:
          claimName: {{ include "collider.fullname" . }}-dragonfly-pvc
      {{- end }}
{{- end }}