[package]
name = "user-responses"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
user-models.workspace = true
chrono.workspace = true
uuid.workspace = true
utoipa.workspace = true