services:
  # Benchmark runner for Criterion and Goose
  bench-runner:
    build:
      context: ../../
      dockerfile: infrastructure/benchmarking/Dockerfile.bench
    container_name: collider_bench_runner
    environment:
      CRITERION_TARGET_URL: "http://app:8080"
      GOOSE_TARGET_URL: "http://app:8080"
    volumes:
      - ./results:/app/results
      - ./:/app/benchmarks
    networks:
      - collider
    depends_on:
      app:
        condition: service_healthy
    profiles:
      - bench

  # K6 Load Testing
  k6:
    image: grafana/k6:latest
    container_name: collider_k6_bench
    environment:
      TARGET_URL: "http://app:8080"
    volumes:
      - ./k6:/scripts
      - ./results:/results
    networks:
      - collider
    depends_on:
      app:
        condition: service_healthy
    profiles:
      - k6

networks:
  collider:
    external: true