{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collider.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "collider.postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "collider.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "collider.postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - configMapRef:
            name: {{ include "collider.fullname" . }}-postgres-config
        - secretRef:
            name: {{ include "collider.fullname" . }}-postgres-secret
        args:
        - postgres
        - -c
        - max_connections={{ .Values.postgres.config.maxConnections }}
        - -c
        - shared_buffers={{ .Values.postgres.config.sharedBuffers }}
        volumeMounts:
        {{- if .Values.postgres.persistence.enabled }}
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        {{- end }}
        {{- if .Values.postgres.healthcheck.enabled }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgres.auth.username }}
          initialDelaySeconds: {{ .Values.postgres.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.postgres.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.postgres.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.postgres.healthcheck.failureThreshold }}
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.postgres.auth.username }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        {{- end }}
        {{- include "collider.resources" .Values.postgres | nindent 8 }}
      volumes:
      {{- if .Values.postgres.persistence.enabled }}
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ include "collider.fullname" . }}-postgres-pvc
      {{- end }}
{{- end }}