[package]
name = "seeder"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "seeder"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
tokio.workspace = true
tokio-util = "0.7"
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true

# CLI and TUI dependencies
ratatui = "0.28"
crossterm = "0.28"
indicatif = "0.17"
dialoguer = "0.11"

# Local dependencies
sql-connection.workspace = true
seeders = { path = "../../libs/seeders" }