[package]
name = "collider"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web framework
axum.workspace = true
tower-http.workspace = true

# Async runtime
tokio.workspace = true

# Database
sea-orm.workspace = true
sqlx.workspace = true

events-http = { path = "../domains/events/http" }
events-commands = { path = "../domains/events/commands" }
analytics-http = { path = "../domains/analytics/http" }
user-http = { path = "../domains/user/http" }
user-commands = { path = "../domains/user/commands" }
test-utils.workspace = true
seeders = { path = "../libs/seeders" }
database-traits.workspace = true
sql-connection.workspace = true
redis-connection.workspace = true


# Serialization
serde.workspace = true
serde_json.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true

# Utils
uuid.workspace = true
chrono.workspace = true
anyhow.workspace = true
thiserror.workspace = true

# Environment
dotenvy.workspace = true

# API Documentation
utoipa.workspace = true
utoipa-rapidoc.workspace = true

[dev-dependencies]
criterion.workspace = true

[features]
default = []
flamegraph = []
