DROP MATERIALIZED VIEW IF EXISTS user_session_summaries CASCADE;
DROP MATERIALIZED VIEW IF EXISTS popular_events CASCADE;
DROP MATERIALIZED VIEW IF EXISTS user_daily_activity CASCADE;
DROP MATERIALIZED VIEW IF EXISTS event_hourly_summaries CASCADE;