[package]
name = "analytics-commands"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
serde_json.workspace = true
utoipa.workspace = true
analytics-models.workspace = true
thiserror = "2.0.12"