[package]
name = "user-models"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-postgres.workspace = true
deadpool-postgres.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true