[package]
name = "user-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
redis-connection.workspace = true
sql-connection.workspace = true
common-errors.workspace = true