[package]
name = "analytics-models"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
utoipa.workspace = true
serde_json.workspace = true