# Cloudflare Tunnel Configuration for Collider
# High-performance tunnel setup with QUIC protocol and optimizations

tunnel: YOUR-TUNNEL-ID-HERE
credentials-file: /home/deploy/.cloudflared/YOUR-TUNNEL-ID.json

# Performance settings for high-throughput applications
protocol: quic                    # QUIC for better performance
loglevel: info
logfile: /var/log/cloudflared.log
metrics: 127.0.0.1:2000          # Metrics endpoint

# Advanced connection settings
connection-timeout: 30s
keep-alive-connections: 100
keep-alive-timeout: 90s

# Route configuration for production deployment
ingress:
  # Main application API
  - hostname: api.yourdomain.com
    service: http://localhost:8080
    originRequest:
      http2Origin: true
      noTLSVerify: true
      disableChunkedEncoding: true    # Better for high RPS
      keepAliveConnections: 100
      keepAliveTimeout: 90s
      connectTimeout: 30s
      
  # Health check endpoint (separate subdomain for monitoring)
  - hostname: health.yourdomain.com
    service: http://localhost:8080/health
    originRequest:
      noTLSVerify: true
      httpHostHeader: "localhost"
      
  # Monitoring dashboard (Grafana)
  - hostname: monitor.yourdomain.com
    service: http://localhost:3000
    originRequest:
      noTLSVerify: true
      httpHostHeader: "localhost"
      
  # Prometheus metrics (if needed externally)
  - hostname: metrics.yourdomain.com
    service: http://localhost:9090
    originRequest:
      noTLSVerify: true
      httpHostHeader: "localhost"
      
  # Frontend application (React)
  - hostname: yourdomain.com
    service: http://localhost:5173
    originRequest:
      http2Origin: true
      noTLSVerify: true
      
  # Catch-all rule (404 for undefined routes)
  - service: http_status:404